In [1]:
import numpy as np
import pandas as pd

pd.set_option("display.max.columns", 100)
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import roc_auc_score
from sklearn.model_selection import StratifiedKFold, cross_val_score, train_test_split

import warnings
warnings.filterwarnings("ignore")

In [2]:
df = pd.read_csv("../data/bank-full.csv")
df.head()

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,y
0,58,management,married,tertiary,no,2143,yes,no,unknown,5,may,261,1,-1,0,unknown,no
1,44,technician,single,secondary,no,29,yes,no,unknown,5,may,151,1,-1,0,unknown,no
2,33,entrepreneur,married,secondary,no,2,yes,yes,unknown,5,may,76,1,-1,0,unknown,no
3,47,blue-collar,married,unknown,no,1506,yes,no,unknown,5,may,92,1,-1,0,unknown,no
4,33,unknown,single,unknown,no,1,no,no,unknown,5,may,198,1,-1,0,unknown,no

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 45211 entries, 0 to 45210
Data columns (total 17 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   age        45211 non-null  int64
 1   job        45211 non-null  str
 2   marital    45211 non-null  str
 3   education  45211 non-null  str
 4   default    45211 non-null  str
 5   balance    45211 non-null  int64
 6   housing    45211 non-null  str
 7   loan       45211 non-null  str
 8   contact    45211 non-null  str
 9   day        45211 non-null  int64
 10  month      45211 non-null  str
 11  duration   45211 non-null  int64
 12  campaign   45211 non-null  int64
 13  pdays      45211 non-null  int64
 14  previous   45211 non-null  int64
 15  poutcome   45211 non-null  str
 16  y          45211 non-null  str
dtypes: int64(7), str(10)
memory usage: 8.1 MB

In [4]:
df.columns[df.dtypes == "str"]

Index(['job', 'marital', 'education', 'default', 'housing', 'loan', 'contact',
       'month', 'poutcome', 'y'],
      dtype='str')

# Обучение без категориальных признаков

In [5]:
df['y'] = df['y'].map({'yes': 1, 'no': 0})
df_no_cat, y = df.loc[:, df.dtypes != "str"].drop("y", axis=1), df["y"]

In [6]:
df_no_cat_part, df_no_cat_valid, y_train_part, y_valid = train_test_split(
    df_no_cat, y, test_size=0.3, stratify=y, random_state=17
)

In [7]:
skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=17)
forest = RandomForestClassifier(random_state=17)

In [8]:
np.mean(cross_val_score(forest, df_no_cat_part, y_train_part, cv=skf, scoring="roc_auc"))

np.float64(0.8694791953707963)

In [9]:
forest.fit(df_no_cat_part, y_train_part)

RandomForestClassifier(random_state=17)

In [10]:
roc_auc_score(y_valid, forest.predict_proba(df_no_cat_valid)[:, 1])

0.8755735302156271

# LabelEncoder для категориальных признаков

In [11]:
from sklearn.preprocessing import LabelEncoder

In [12]:
label_encoder = LabelEncoder()

df_cat_label_enc = df.copy().drop("y", axis=1)
for col in df.columns[df.dtypes == "str"]:
    df_cat_label_enc[col] = label_encoder.fit_transform(df_cat_label_enc[col])

In [13]:
df_cat_label_enc.shape

(45211, 16)

In [14]:
df_cat_label_enc_part, df_cat_label_enc_valid = train_test_split(
    df_cat_label_enc, test_size=0.3, stratify=y, random_state=17
)

In [15]:
np.mean(cross_val_score(
        forest, df_cat_label_enc_part, y_train_part, cv=skf, scoring="roc_auc"
    )
)

np.float64(0.9248951709439887)

In [16]:
forest.fit(df_cat_label_enc_part, y_train_part)

RandomForestClassifier(random_state=17)

In [17]:
roc_auc_score(y_valid, forest.predict_proba(df_cat_label_enc_valid)[:, 1])

0.9299445971297962

# Бинаризация категориальных признаков

In [18]:
df_cat_dummies = pd.get_dummies(df, columns=df.columns[df.dtypes == "str"]).drop("y", axis=1)

In [19]:
df_cat_dummies.shape

(45211, 51)

In [20]:
df_cat_dummies_part, df_cat_dummies_valid = train_test_split(
    df_cat_dummies, test_size=0.3, stratify=y, random_state=17
)

In [21]:
np.mean(cross_val_score(
        forest, df_cat_dummies_part, y_train_part, cv=skf, scoring="roc_auc"
    )
)

np.float64(0.9269823520704952)

In [22]:
forest.fit(df_cat_dummies_part, y_train_part)

RandomForestClassifier(random_state=17)

In [23]:
roc_auc_score(y_valid, forest.predict_proba(df_cat_dummies_valid)[:, 1])

0.9304830688140506

# Попарные взаимодействия признаков

In [24]:
df_interact = df.copy()

In [25]:
cat_features = df.columns[df.dtypes == "str"]
for i, col1 in enumerate(cat_features):
    for j, col2 in enumerate(cat_features[i + 1 :]):
        df_interact[col1 + "_" + col2] = df_interact[col1] + "_" + df_interact[col2]

In [26]:
df_interact.shape

(45211, 53)

In [27]:
df_interact.head()

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,y,job_marital,job_education,job_default,job_housing,job_loan,job_contact,job_month,job_poutcome,marital_education,marital_default,marital_housing,marital_loan,marital_contact,marital_month,marital_poutcome,education_default,education_housing,education_loan,education_contact,education_month,education_poutcome,default_housing,default_loan,default_contact,default_month,default_poutcome,housing_loan,housing_contact,housing_month,housing_poutcome,loan_contact,loan_month,loan_poutcome,contact_month,contact_poutcome,month_poutcome
0,58,management,married,tertiary,no,2143,yes,no,unknown,5,may,261,1,-1,0,unknown,0,management_married,management_tertiary,management_no,management_yes,management_no,management_unknown,management_may,management_unknown,married_tertiary,married_no,married_yes,married_no,married_unknown,married_may,married_unknown,tertiary_no,tertiary_yes,tertiary_no,tertiary_unknown,tertiary_may,tertiary_unknown,no_yes,no_no,no_unknown,no_may,no_unknown,yes_no,yes_unknown,yes_may,yes_unknown,no_unknown,no_may,no_unknown,unknown_may,unknown_unknown,may_unknown
1,44,technician,single,secondary,no,29,yes,no,unknown,5,may,151,1,-1,0,unknown,0,technician_single,technician_secondary,technician_no,technician_yes,technician_no,technician_unknown,technician_may,technician_unknown,single_secondary,single_no,single_yes,single_no,single_unknown,single_may,single_unknown,secondary_no,secondary_yes,secondary_no,secondary_unknown,secondary_may,secondary_unknown,no_yes,no_no,no_unknown,no_may,no_unknown,yes_no,yes_unknown,yes_may,yes_unknown,no_unknown,no_may,no_unknown,unknown_may,unknown_unknown,may_unknown
2,33,entrepreneur,married,secondary,no,2,yes,yes,unknown,5,may,76,1,-1,0,unknown,0,entrepreneur_married,entrepreneur_secondary,entrepreneur_no,entrepreneur_yes,entrepreneur_yes,entrepreneur_unknown,entrepreneur_may,entrepreneur_unknown,married_secondary,married_no,married_yes,married_yes,married_unknown,married_may,married_unknown,secondary_no,secondary_yes,secondary_yes,secondary_unknown,secondary_may,secondary_unknown,no_yes,no_yes,no_unknown,no_may,no_unknown,yes_yes,yes_unknown,yes_may,yes_unknown,yes_unknown,yes_may,yes_unknown,unknown_may,unknown_unknown,may_unknown
3,47,blue-collar,married,unknown,no,1506,yes,no,unknown,5,may,92,1,-1,0,unknown,0,blue-collar_married,blue-collar_unknown,blue-collar_no,blue-collar_yes,blue-collar_no,blue-collar_unknown,blue-collar_may,blue-collar_unknown,married_unknown,married_no,married_yes,married_no,married_unknown,married_may,married_unknown,unknown_no,unknown_yes,unknown_no,unknown_unknown,unknown_may,unknown_unknown,no_yes,no_no,no_unknown,no_may,no_unknown,yes_no,yes_unknown,yes_may,yes_unknown,no_unknown,no_may,no_unknown,unknown_may,unknown_unknown,may_unknown
4,33,unknown,single,unknown,no,1,no,no,unknown,5,may,198,1,-1,0,unknown,0,unknown_single,unknown_unknown,unknown_no,unknown_no,unknown_no,unknown_unknown,unknown_may,unknown_unknown,single_unknown,single_no,single_no,single_no,single_unknown,single_may,single_unknown,unknown_no,unknown_no,unknown_no,unknown_unknown,unknown_may,unknown_unknown,no_no,no_no,no_unknown,no_may,no_unknown,no_no,no_unknown,no_may,no_unknown,no_unknown,no_may,no_unknown,unknown_may,unknown_unknown,may_unknown

# Бинаризация категориальных признаков + попарные взаимодействия

In [28]:
df_interact_cat_dummies = pd.get_dummies(
    df_interact, columns=df_interact.columns[df_interact.dtypes == "str"]
).drop("y", axis=1)

In [29]:
df_interact_cat_dummies.shape

(45211, 841)

In [30]:
df_interact_cat_dummies_part, df_interact_cat_dummies_valid = train_test_split(
    df_interact_cat_dummies, test_size=0.3, stratify=y, random_state=17
)

In [31]:
np.mean(cross_val_score(
        forest, df_interact_cat_dummies_part, y_train_part, cv=skf, scoring="roc_auc"
    )
)

np.float64(0.8956521436977407)

In [32]:
forest.fit(df_interact_cat_dummies_part, y_train_part)

RandomForestClassifier(random_state=17)

In [33]:
roc_auc_score(y_valid, forest.predict_proba(df_interact_cat_dummies_valid)[:, 1])

0.9003708483688464

In [34]:
from sklearn.linear_model import LogisticRegression

logit = LogisticRegression(random_state=17)

In [35]:
np.mean(cross_val_score(
        logit, df_interact_cat_dummies_part, y_train_part, cv=skf, scoring="roc_auc"
    )
)

np.float64(0.8739336839235137)

In [36]:
logit.fit(df_interact_cat_dummies_part, y_train_part)

LogisticRegression(random_state=17)

In [37]:
roc_auc_score(y_valid, logit.predict_proba(df_interact_cat_dummies_valid)[:, 1])

0.8837854469964722

# Mean Target

In [38]:
skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=1)

In [39]:
train_df, y = df.copy(), df["y"]
train_df_part, valid_df, y_train_part, y_valid = train_test_split(
    train_df.drop("y", axis=1), y, test_size=0.3, stratify=y, random_state=17
)

In [40]:
def mean_target_enc(train_df, y_train, valid_df, skf):
    glob_mean = y_train.mean()
    train_df = pd.concat([train_df, pd.Series(y_train, name="y")], axis=1)
    new_train_df = train_df.copy()
    cat_features = train_df.columns[train_df.dtypes == "str"].tolist()

    for col in cat_features:
        new_train_df[col + "_mean_target"] = [glob_mean for _ in range(new_train_df.shape[0])]

    for train_idx, valid_idx in skf.split(train_df, y_train):
        train_df_cv, valid_df_cv = (
            train_df.iloc[train_idx, :],
            train_df.iloc[valid_idx, :],
        )

        for col in cat_features:
            means = valid_df_cv[col].map(train_df_cv.groupby(col)["y"].mean())
            valid_df_cv[col + "_mean_target"] = means.fillna(glob_mean)

        new_train_df.iloc[valid_idx] = valid_df_cv

    new_train_df.drop(cat_features + ["y"], axis=1, inplace=True)

    for col in cat_features:
        means = valid_df[col].map(train_df.groupby(col)["y"].mean())
        valid_df[col + "_mean_target"] = means.fillna(glob_mean)

    valid_df.drop(train_df.columns[train_df.dtypes == "str"], axis=1, inplace=True)

    return new_train_df, valid_df

In [41]:
train_mean_target_part, valid_mean_target = mean_target_enc(train_df_part, y_train_part, valid_df, skf)

In [42]:
np.mean(cross_val_score(
        forest, train_mean_target_part, y_train_part, cv=skf, scoring="roc_auc"
    )
)

np.float64(0.9258978857660949)

In [43]:
forest.fit(train_mean_target_part, y_train_part)

RandomForestClassifier(random_state=17)

In [44]:
roc_auc_score(y_valid, forest.predict_proba(valid_mean_target)[:, 1])

0.9296285902737651

# Mean Target + попарные взаимодействия

In [45]:
skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=1)

In [46]:
train_df, y = df_interact.drop("y", axis=1).copy(), df_interact["y"]
train_df_part, valid_df, y_train_part, y_valid = train_test_split(
    train_df, y, test_size=0.3, stratify=y, random_state=17
)

In [47]:
train_mean_target_part, valid_mean_target = mean_target_enc(
    train_df_part, y_train_part, valid_df, skf
)

In [48]:
np.mean(cross_val_score(
        forest, train_mean_target_part, y_train_part, cv=skf, scoring="roc_auc"
    )
)

np.float64(0.9221840696923331)

In [49]:
forest.fit(train_mean_target_part, y_train_part)

RandomForestClassifier(random_state=17)

In [50]:
roc_auc_score(y_valid, forest.predict_proba(valid_mean_target)[:, 1])

0.9256619190141744

# Catboost

In [51]:
from catboost import CatBoostClassifier

In [52]:
ctb = CatBoostClassifier(random_seed=17)

In [53]:
train_df, y = df.drop("y", axis=1), df["y"]
train_df_part, valid_df, y_train_part, y_valid = train_test_split(
    train_df, y, test_size=0.3, stratify=y, random_state=17
)

In [54]:
cat_features_idx = np.where(train_df_part.dtypes == "str")[0].tolist()

In [55]:
%%time
cv_scores = []
for train_idx, test_idx in skf.split(train_df_part, y_train_part):
    cv_train_df, cv_valid_df = (
        train_df_part.iloc[train_idx, :],
        train_df_part.iloc[test_idx, :],
    )
    y_cv_train, y_cv_valid = y_train_part.iloc[train_idx], y_train_part.iloc[test_idx]

    ctb.fit(cv_train_df, y_cv_train, cat_features=cat_features_idx)

    cv_scores.append(roc_auc_score(y_cv_valid, ctb.predict_proba(cv_valid_df)[:, 1]))

Learning rate set to 0.040944
0:	learn: 0.6424143	total: 77.1ms	remaining: 1m 17s
1:	learn: 0.6046442	total: 92ms	remaining: 45.9s
2:	learn: 0.5707668	total: 111ms	remaining: 36.7s
3:	learn: 0.5370097	total: 126ms	remaining: 31.3s
4:	learn: 0.5090134	total: 140ms	remaining: 27.9s
5:	learn: 0.4861823	total: 153ms	remaining: 25.3s
6:	learn: 0.4609993	total: 168ms	remaining: 23.8s
7:	learn: 0.4403509	total: 184ms	remaining: 22.8s
8:	learn: 0.4227504	total: 197ms	remaining: 21.7s
9:	learn: 0.4054272	total: 212ms	remaining: 21s
10:	learn: 0.3884413	total: 225ms	remaining: 20.2s
11:	learn: 0.3726519	total: 240ms	remaining: 19.8s
12:	learn: 0.3600288	total: 254ms	remaining: 19.3s
13:	learn: 0.3486741	total: 267ms	remaining: 18.8s
14:	learn: 0.3385727	total: 279ms	remaining: 18.3s
15:	learn: 0.3280064	total: 292ms	remaining: 18s
16:	learn: 0.3194867	total: 305ms	remaining: 17.7s
17:	learn: 0.3122800	total: 321ms	remaining: 17.5s
18:	learn: 0.3066110	total: 331ms	remaining: 17.1s
19:	learn: 0.3011421	total: 345ms	remaining: 16.9s
20:	learn: 0.2938948	total: 358ms	remaining: 16.7s
21:	learn: 0.2876083	total: 370ms	remaining: 16.5s
22:	learn: 0.2826878	total: 381ms	remaining: 16.2s
23:	learn: 0.2782045	total: 394ms	remaining: 16s
24:	learn: 0.2740210	total: 407ms	remaining: 15.9s
25:	learn: 0.2703199	total: 421ms	remaining: 15.8s
26:	learn: 0.2664258	total: 436ms	remaining: 15.7s
27:	learn: 0.2634305	total: 449ms	remaining: 15.6s
28:	learn: 0.2607604	total: 463ms	remaining: 15.5s
29:	learn: 0.2579740	total: 475ms	remaining: 15.4s
30:	learn: 0.2544363	total: 488ms	remaining: 15.2s
31:	learn: 0.2517776	total: 501ms	remaining: 15.1s
32:	learn: 0.2488224	total: 513ms	remaining: 15s
33:	learn: 0.2474620	total: 523ms	remaining: 14.8s
34:	learn: 0.2452666	total: 535ms	remaining: 14.7s
35:	learn: 0.2431546	total: 547ms	remaining: 14.6s
36:	learn: 0.2410390	total: 560ms	remaining: 14.6s
37:	learn: 0.2389795	total: 572ms	remaining: 14.5s
38:	learn: 0.2374620	total: 584ms	remaining: 14.4s
39:	learn: 0.2359934	total: 597ms	remaining: 14.3s
40:	learn: 0.2344005	total: 610ms	remaining: 14.3s
41:	learn: 0.2332002	total: 621ms	remaining: 14.2s
42:	learn: 0.2321106	total: 637ms	remaining: 14.2s
43:	learn: 0.2309178	total: 650ms	remaining: 14.1s
44:	learn: 0.2294997	total: 662ms	remaining: 14.1s
45:	learn: 0.2284206	total: 678ms	remaining: 14.1s
46:	learn: 0.2276167	total: 689ms	remaining: 14s
47:	learn: 0.2264905	total: 701ms	remaining: 13.9s
48:	learn: 0.2247724	total: 711ms	remaining: 13.8s
49:	learn: 0.2241481	total: 722ms	remaining: 13.7s
50:	learn: 0.2235649	total: 735ms	remaining: 13.7s
51:	learn: 0.2227317	total: 748ms	remaining: 13.6s
52:	learn: 0.2222051	total: 762ms	remaining: 13.6s
53:	learn: 0.2206106	total: 770ms	remaining: 13.5s
54:	learn: 0.2196337	total: 780ms	remaining: 13.4s
55:	learn: 0.2188531	total: 790ms	remaining: 13.3s
56:	learn: 0.2183867	total: 800ms	remaining: 13.2s
57:	learn: 0.2176382	total: 811ms	remaining: 13.2s
58:	learn: 0.2171920	total: 822ms	remaining: 13.1s
59:	learn: 0.2165493	total: 834ms	remaining: 13.1s
60:	learn: 0.2161717	total: 845ms	remaining: 13s
61:	learn: 0.2158575	total: 857ms	remaining: 13s
62:	learn: 0.2154668	total: 870ms	remaining: 12.9s
63:	learn: 0.2147450	total: 881ms	remaining: 12.9s
64:	learn: 0.2144582	total: 892ms	remaining: 12.8s
65:	learn: 0.2141222	total: 901ms	remaining: 12.8s
66:	learn: 0.2133695	total: 912ms	remaining: 12.7s
67:	learn: 0.2130512	total: 922ms	remaining: 12.6s
68:	learn: 0.2124735	total: 932ms	remaining: 12.6s
69:	learn: 0.2122427	total: 943ms	remaining: 12.5s
70:	learn: 0.2118905	total: 954ms	remaining: 12.5s
71:	learn: 0.2115615	total: 965ms	remaining: 12.4s
72:	learn: 0.2112630	total: 976ms	remaining: 12.4s
73:	learn: 0.2108492	total: 987ms	remaining: 12.3s
74:	learn: 0.2106029	total: 998ms	remaining: 12.3s
75:	learn: 0.2103103	total: 1.01s	remaining: 12.3s
76:	learn: 0.2101119	total: 1.02s	remaining: 12.2s
77:	learn: 0.2097718	total: 1.03s	remaining: 12.2s
78:	learn: 0.2094510	total: 1.04s	remaining: 12.2s
79:	learn: 0.2091722	total: 1.06s	remaining: 12.2s
80:	learn: 0.2089660	total: 1.07s	remaining: 12.2s
81:	learn: 0.2086812	total: 1.09s	remaining: 12.2s
82:	learn: 0.2083487	total: 1.1s	remaining: 12.2s
83:	learn: 0.2080274	total: 1.11s	remaining: 12.1s
84:	learn: 0.2076057	total: 1.13s	remaining: 12.1s
85:	learn: 0.2073577	total: 1.14s	remaining: 12.1s
86:	learn: 0.2072336	total: 1.15s	remaining: 12.1s
87:	learn: 0.2070234	total: 1.16s	remaining: 12s
88:	learn: 0.2069006	total: 1.17s	remaining: 12s
89:	learn: 0.2066182	total: 1.18s	remaining: 12s
90:	learn: 0.2064029	total: 1.19s	remaining: 11.9s
91:	learn: 0.2063358	total: 1.21s	remaining: 11.9s
92:	learn: 0.2061052	total: 1.22s	remaining: 11.9s
93:	learn: 0.2058533	total: 1.23s	remaining: 11.9s
94:	learn: 0.2056115	total: 1.24s	remaining: 11.8s
95:	learn: 0.2054438	total: 1.25s	remaining: 11.8s
96:	learn: 0.2052806	total: 1.26s	remaining: 11.8s
97:	learn: 0.2049607	total: 1.27s	remaining: 11.7s
98:	learn: 0.2048670	total: 1.29s	remaining: 11.7s
99:	learn: 0.2046567	total: 1.3s	remaining: 11.7s
100:	learn: 0.2045187	total: 1.31s	remaining: 11.7s
101:	learn: 0.2042418	total: 1.32s	remaining: 11.7s
102:	learn: 0.2041085	total: 1.33s	remaining: 11.6s
103:	learn: 0.2039585	total: 1.35s	remaining: 11.6s
104:	learn: 0.2039381	total: 1.35s	remaining: 11.5s
105:	learn: 0.2036450	total: 1.37s	remaining: 11.5s
106:	learn: 0.2035633	total: 1.38s	remaining: 11.5s
107:	learn: 0.2033826	total: 1.39s	remaining: 11.5s
108:	learn: 0.2031001	total: 1.41s	remaining: 11.5s
109:	learn: 0.2029784	total: 1.42s	remaining: 11.5s
110:	learn: 0.2028018	total: 1.43s	remaining: 11.5s
111:	learn: 0.2026865	total: 1.45s	remaining: 11.5s
112:	learn: 0.2024595	total: 1.46s	remaining: 11.5s
113:	learn: 0.2023455	total: 1.47s	remaining: 11.4s
114:	learn: 0.2022517	total: 1.49s	remaining: 11.4s
115:	learn: 0.2021252	total: 1.5s	remaining: 11.4s
116:	learn: 0.2020112	total: 1.51s	remaining: 11.4s
117:	learn: 0.2017435	total: 1.52s	remaining: 11.4s
118:	learn: 0.2016786	total: 1.53s	remaining: 11.4s
119:	learn: 0.2014922	total: 1.54s	remaining: 11.3s
120:	learn: 0.2012282	total: 1.56s	remaining: 11.3s
121:	learn: 0.2010168	total: 1.57s	remaining: 11.3s
122:	learn: 0.2009983	total: 1.57s	remaining: 11.2s
123:	learn: 0.2009224	total: 1.59s	remaining: 11.2s
124:	learn: 0.2007361	total: 1.6s	remaining: 11.2s
125:	learn: 0.2006732	total: 1.61s	remaining: 11.2s
126:	learn: 0.2005561	total: 1.62s	remaining: 11.2s
127:	learn: 0.2004961	total: 1.63s	remaining: 11.1s
128:	learn: 0.2003775	total: 1.65s	remaining: 11.1s
129:	learn: 0.2002452	total: 1.66s	remaining: 11.1s
130:	learn: 0.2000346	total: 1.67s	remaining: 11.1s
131:	learn: 0.1998842	total: 1.68s	remaining: 11.1s
132:	learn: 0.1997356	total: 1.7s	remaining: 11.1s
133:	learn: 0.1995987	total: 1.71s	remaining: 11s
134:	learn: 0.1995258	total: 1.72s	remaining: 11s
135:	learn: 0.1994011	total: 1.73s	remaining: 11s
136:	learn: 0.1992640	total: 1.74s	remaining: 10.9s
137:	learn: 0.1990842	total: 1.75s	remaining: 10.9s
138:	learn: 0.1989909	total: 1.76s	remaining: 10.9s
139:	learn: 0.1989430	total: 1.77s	remaining: 10.8s
140:	learn: 0.1988101	total: 1.78s	remaining: 10.8s
141:	learn: 0.1987252	total: 1.79s	remaining: 10.8s
142:	learn: 0.1986399	total: 1.8s	remaining: 10.8s
143:	learn: 0.1984175	total: 1.82s	remaining: 10.8s
144:	learn: 0.1983355	total: 1.83s	remaining: 10.8s
145:	learn: 0.1982258	total: 1.84s	remaining: 10.8s
146:	learn: 0.1981332	total: 1.86s	remaining: 10.8s
147:	learn: 0.1980812	total: 1.87s	remaining: 10.8s
148:	learn: 0.1979189	total: 1.88s	remaining: 10.8s
149:	learn: 0.1977353	total: 1.89s	remaining: 10.7s
150:	learn: 0.1976250	total: 1.9s	remaining: 10.7s
151:	learn: 0.1975737	total: 1.92s	remaining: 10.7s
152:	learn: 0.1974651	total: 1.93s	remaining: 10.7s
153:	learn: 0.1973730	total: 1.95s	remaining: 10.7s
154:	learn: 0.1972677	total: 1.96s	remaining: 10.7s
155:	learn: 0.1970192	total: 1.97s	remaining: 10.7s
156:	learn: 0.1969340	total: 1.99s	remaining: 10.7s
157:	learn: 0.1967701	total: 2s	remaining: 10.7s
158:	learn: 0.1966807	total: 2.01s	remaining: 10.6s
159:	learn: 0.1966520	total: 2.02s	remaining: 10.6s
160:	learn: 0.1965549	total: 2.03s	remaining: 10.6s
161:	learn: 0.1964858	total: 2.04s	remaining: 10.6s
162:	learn: 0.1963460	total: 2.06s	remaining: 10.6s
163:	learn: 0.1962984	total: 2.07s	remaining: 10.6s
164:	learn: 0.1962375	total: 2.09s	remaining: 10.6s
165:	learn: 0.1962165	total: 2.1s	remaining: 10.6s
166:	learn: 0.1961212	total: 2.11s	remaining: 10.5s
167:	learn: 0.1960366	total: 2.13s	remaining: 10.5s
168:	learn: 0.1959470	total: 2.14s	remaining: 10.5s
169:	learn: 0.1959439	total: 2.15s	remaining: 10.5s
170:	learn: 0.1957324	total: 2.16s	remaining: 10.5s
171:	learn: 0.1954745	total: 2.17s	remaining: 10.4s
172:	learn: 0.1952890	total: 2.18s	remaining: 10.4s
173:	learn: 0.1949998	total: 2.19s	remaining: 10.4s
174:	learn: 0.1949610	total: 2.21s	remaining: 10.4s
175:	learn: 0.1948822	total: 2.22s	remaining: 10.4s
176:	learn: 0.1947833	total: 2.23s	remaining: 10.4s
177:	learn: 0.1946626	total: 2.24s	remaining: 10.3s
178:	learn: 0.1944021	total: 2.25s	remaining: 10.3s
179:	learn: 0.1943760	total: 2.26s	remaining: 10.3s
180:	learn: 0.1943226	total: 2.27s	remaining: 10.3s
181:	learn: 0.1941365	total: 2.28s	remaining: 10.3s
182:	learn: 0.1940292	total: 2.29s	remaining: 10.2s
183:	learn: 0.1938831	total: 2.3s	remaining: 10.2s
184:	learn: 0.1937991	total: 2.31s	remaining: 10.2s
185:	learn: 0.1937638	total: 2.32s	remaining: 10.2s
186:	learn: 0.1937393	total: 2.33s	remaining: 10.1s
187:	learn: 0.1936627	total: 2.34s	remaining: 10.1s
188:	learn: 0.1935825	total: 2.35s	remaining: 10.1s
189:	learn: 0.1935003	total: 2.36s	remaining: 10.1s
190:	learn: 0.1934465	total: 2.37s	remaining: 10.1s
191:	learn: 0.1932957	total: 2.38s	remaining: 10s
192:	learn: 0.1930509	total: 2.39s	remaining: 10s
193:	learn: 0.1929901	total: 2.4s	remaining: 9.98s
194:	learn: 0.1928990	total: 2.41s	remaining: 9.96s
195:	learn: 0.1927407	total: 2.42s	remaining: 9.94s
196:	learn: 0.1924983	total: 2.43s	remaining: 9.92s
197:	learn: 0.1924909	total: 2.44s	remaining: 9.89s
198:	learn: 0.1923567	total: 2.45s	remaining: 9.87s
199:	learn: 0.1923153	total: 2.46s	remaining: 9.84s
200:	learn: 0.1922122	total: 2.47s	remaining: 9.82s
201:	learn: 0.1921745	total: 2.48s	remaining: 9.81s
202:	learn: 0.1921400	total: 2.49s	remaining: 9.78s
203:	learn: 0.1920945	total: 2.5s	remaining: 9.77s
204:	learn: 0.1920686	total: 2.51s	remaining: 9.74s
205:	learn: 0.1919992	total: 2.52s	remaining: 9.73s
206:	learn: 0.1919650	total: 2.53s	remaining: 9.71s
207:	learn: 0.1917546	total: 2.55s	remaining: 9.7s
208:	learn: 0.1916547	total: 2.56s	remaining: 9.68s
209:	learn: 0.1916176	total: 2.57s	remaining: 9.67s
210:	learn: 0.1915512	total: 2.58s	remaining: 9.66s
211:	learn: 0.1914537	total: 2.59s	remaining: 9.64s
212:	learn: 0.1913443	total: 2.61s	remaining: 9.63s
213:	learn: 0.1913205	total: 2.62s	remaining: 9.62s
214:	learn: 0.1911625	total: 2.63s	remaining: 9.6s
215:	learn: 0.1910157	total: 2.64s	remaining: 9.59s
216:	learn: 0.1909877	total: 2.65s	remaining: 9.57s
217:	learn: 0.1908818	total: 2.66s	remaining: 9.54s
218:	learn: 0.1908189	total: 2.67s	remaining: 9.53s
219:	learn: 0.1908112	total: 2.68s	remaining: 9.5s
220:	learn: 0.1907441	total: 2.69s	remaining: 9.48s
221:	learn: 0.1906095	total: 2.7s	remaining: 9.47s
222:	learn: 0.1905758	total: 2.71s	remaining: 9.44s
223:	learn: 0.1905062	total: 2.72s	remaining: 9.42s
224:	learn: 0.1904010	total: 2.73s	remaining: 9.41s
225:	learn: 0.1902923	total: 2.74s	remaining: 9.39s
226:	learn: 0.1901881	total: 2.75s	remaining: 9.38s
227:	learn: 0.1901339	total: 2.76s	remaining: 9.36s
228:	learn: 0.1900428	total: 2.77s	remaining: 9.34s
229:	learn: 0.1899984	total: 2.79s	remaining: 9.33s
230:	learn: 0.1898581	total: 2.8s	remaining: 9.31s
231:	learn: 0.1898234	total: 2.81s	remaining: 9.3s
232:	learn: 0.1898010	total: 2.82s	remaining: 9.28s
233:	learn: 0.1896948	total: 2.83s	remaining: 9.26s
234:	learn: 0.1896628	total: 2.84s	remaining: 9.24s
235:	learn: 0.1895917	total: 2.85s	remaining: 9.23s
236:	learn: 0.1895477	total: 2.86s	remaining: 9.21s
237:	learn: 0.1894735	total: 2.87s	remaining: 9.2s
238:	learn: 0.1893450	total: 2.88s	remaining: 9.18s
239:	learn: 0.1893063	total: 2.89s	remaining: 9.16s
240:	learn: 0.1892012	total: 2.9s	remaining: 9.15s
241:	learn: 0.1890202	total: 2.92s	remaining: 9.13s
242:	learn: 0.1889176	total: 2.93s	remaining: 9.13s
243:	learn: 0.1888268	total: 2.94s	remaining: 9.12s
244:	learn: 0.1887089	total: 2.95s	remaining: 9.1s
245:	learn: 0.1884708	total: 2.97s	remaining: 9.09s
246:	learn: 0.1884698	total: 2.97s	remaining: 9.06s
247:	learn: 0.1883692	total: 2.98s	remaining: 9.04s
248:	learn: 0.1883325	total: 2.99s	remaining: 9.03s
249:	learn: 0.1883147	total: 3s	remaining: 9.01s
250:	learn: 0.1882556	total: 3.01s	remaining: 8.99s
251:	learn: 0.1881031	total: 3.03s	remaining: 8.99s
252:	learn: 0.1880487	total: 3.04s	remaining: 8.98s
253:	learn: 0.1879992	total: 3.05s	remaining: 8.97s
254:	learn: 0.1879772	total: 3.07s	remaining: 8.96s
255:	learn: 0.1879118	total: 3.08s	remaining: 8.95s
256:	learn: 0.1877145	total: 3.09s	remaining: 8.93s
257:	learn: 0.1875682	total: 3.11s	remaining: 8.94s
258:	learn: 0.1875256	total: 3.12s	remaining: 8.92s
259:	learn: 0.1874601	total: 3.13s	remaining: 8.9s
260:	learn: 0.1873669	total: 3.14s	remaining: 8.89s
261:	learn: 0.1871770	total: 3.15s	remaining: 8.87s
262:	learn: 0.1871497	total: 3.16s	remaining: 8.86s
263:	learn: 0.1870705	total: 3.17s	remaining: 8.85s
264:	learn: 0.1869339	total: 3.19s	remaining: 8.84s
265:	learn: 0.1868587	total: 3.2s	remaining: 8.82s
266:	learn: 0.1866849	total: 3.21s	remaining: 8.81s
267:	learn: 0.1864707	total: 3.22s	remaining: 8.79s
268:	learn: 0.1864049	total: 3.23s	remaining: 8.79s
269:	learn: 0.1863102	total: 3.25s	remaining: 8.79s
270:	learn: 0.1862266	total: 3.26s	remaining: 8.77s
271:	learn: 0.1861444	total: 3.27s	remaining: 8.76s
272:	learn: 0.1861210	total: 3.29s	remaining: 8.75s
273:	learn: 0.1858837	total: 3.29s	remaining: 8.73s
274:	learn: 0.1857260	total: 3.31s	remaining: 8.72s
275:	learn: 0.1855709	total: 3.32s	remaining: 8.71s
276:	learn: 0.1855074	total: 3.33s	remaining: 8.69s
277:	learn: 0.1854394	total: 3.34s	remaining: 8.68s
278:	learn: 0.1853643	total: 3.35s	remaining: 8.66s
279:	learn: 0.1853267	total: 3.36s	remaining: 8.65s
280:	learn: 0.1852259	total: 3.37s	remaining: 8.63s
281:	learn: 0.1851389	total: 3.38s	remaining: 8.62s
282:	learn: 0.1850685	total: 3.4s	remaining: 8.6s
283:	learn: 0.1849570	total: 3.41s	remaining: 8.59s
284:	learn: 0.1848844	total: 3.42s	remaining: 8.57s
285:	learn: 0.1847646	total: 3.43s	remaining: 8.56s
286:	learn: 0.1846443	total: 3.44s	remaining: 8.55s
287:	learn: 0.1846092	total: 3.46s	remaining: 8.54s
288:	learn: 0.1845135	total: 3.47s	remaining: 8.54s
289:	learn: 0.1843879	total: 3.48s	remaining: 8.52s
290:	learn: 0.1843088	total: 3.49s	remaining: 8.51s
291:	learn: 0.1841440	total: 3.5s	remaining: 8.49s
292:	learn: 0.1840644	total: 3.52s	remaining: 8.48s
293:	learn: 0.1840223	total: 3.53s	remaining: 8.47s
294:	learn: 0.1839695	total: 3.54s	remaining: 8.46s
295:	learn: 0.1838121	total: 3.56s	remaining: 8.46s
296:	learn: 0.1836983	total: 3.57s	remaining: 8.45s
297:	learn: 0.1836561	total: 3.58s	remaining: 8.43s
298:	learn: 0.1835781	total: 3.59s	remaining: 8.42s
299:	learn: 0.1834229	total: 3.61s	remaining: 8.42s
300:	learn: 0.1833604	total: 3.62s	remaining: 8.41s
301:	learn: 0.1832679	total: 3.63s	remaining: 8.39s
302:	learn: 0.1832243	total: 3.64s	remaining: 8.38s
303:	learn: 0.1831811	total: 3.65s	remaining: 8.36s
304:	learn: 0.1831462	total: 3.66s	remaining: 8.35s
305:	learn: 0.1830266	total: 3.68s	remaining: 8.34s
306:	learn: 0.1829414	total: 3.69s	remaining: 8.32s
307:	learn: 0.1828228	total: 3.7s	remaining: 8.31s
308:	learn: 0.1827412	total: 3.71s	remaining: 8.3s
309:	learn: 0.1826398	total: 3.72s	remaining: 8.29s
310:	learn: 0.1826005	total: 3.73s	remaining: 8.27s
311:	learn: 0.1825184	total: 3.74s	remaining: 8.26s
312:	learn: 0.1824812	total: 3.75s	remaining: 8.24s
313:	learn: 0.1823741	total: 3.77s	remaining: 8.23s
314:	learn: 0.1823118	total: 3.78s	remaining: 8.22s
315:	learn: 0.1821301	total: 3.79s	remaining: 8.21s
316:	learn: 0.1821095	total: 3.81s	remaining: 8.21s
317:	learn: 0.1819604	total: 3.83s	remaining: 8.2s
318:	learn: 0.1819222	total: 3.84s	remaining: 8.2s
319:	learn: 0.1818936	total: 3.85s	remaining: 8.18s
320:	learn: 0.1818670	total: 3.86s	remaining: 8.18s
321:	learn: 0.1817635	total: 3.88s	remaining: 8.17s
322:	learn: 0.1816948	total: 3.89s	remaining: 8.16s
323:	learn: 0.1815839	total: 3.9s	remaining: 8.14s
324:	learn: 0.1815460	total: 3.92s	remaining: 8.13s
325:	learn: 0.1813924	total: 3.93s	remaining: 8.12s
326:	learn: 0.1813101	total: 3.94s	remaining: 8.11s
327:	learn: 0.1812755	total: 3.95s	remaining: 8.1s
328:	learn: 0.1811396	total: 3.97s	remaining: 8.1s
329:	learn: 0.1811043	total: 3.98s	remaining: 8.09s
330:	learn: 0.1810573	total: 4s	remaining: 8.08s
331:	learn: 0.1810044	total: 4.01s	remaining: 8.08s
332:	learn: 0.1809781	total: 4.03s	remaining: 8.07s
333:	learn: 0.1809111	total: 4.04s	remaining: 8.06s
334:	learn: 0.1808496	total: 4.06s	remaining: 8.05s
335:	learn: 0.1807919	total: 4.07s	remaining: 8.05s
336:	learn: 0.1807467	total: 4.09s	remaining: 8.04s
337:	learn: 0.1807124	total: 4.1s	remaining: 8.03s
338:	learn: 0.1806763	total: 4.11s	remaining: 8.02s
339:	learn: 0.1804399	total: 4.13s	remaining: 8.01s
340:	learn: 0.1803386	total: 4.14s	remaining: 8s
341:	learn: 0.1801977	total: 4.15s	remaining: 7.98s
342:	learn: 0.1801488	total: 4.16s	remaining: 7.97s
343:	learn: 0.1801150	total: 4.17s	remaining: 7.96s
344:	learn: 0.1800031	total: 4.18s	remaining: 7.94s
345:	learn: 0.1799618	total: 4.19s	remaining: 7.92s
346:	learn: 0.1799307	total: 4.2s	remaining: 7.91s
347:	learn: 0.1798808	total: 4.21s	remaining: 7.9s
348:	learn: 0.1798227	total: 4.23s	remaining: 7.88s
349:	learn: 0.1797986	total: 4.24s	remaining: 7.87s
350:	learn: 0.1797097	total: 4.25s	remaining: 7.86s
351:	learn: 0.1796307	total: 4.26s	remaining: 7.85s
352:	learn: 0.1794594	total: 4.28s	remaining: 7.84s
353:	learn: 0.1793899	total: 4.29s	remaining: 7.83s
354:	learn: 0.1793313	total: 4.3s	remaining: 7.81s
355:	learn: 0.1792705	total: 4.31s	remaining: 7.8s
356:	learn: 0.1791863	total: 4.32s	remaining: 7.78s
357:	learn: 0.1790870	total: 4.33s	remaining: 7.77s
358:	learn: 0.1790343	total: 4.34s	remaining: 7.76s
359:	learn: 0.1789810	total: 4.36s	remaining: 7.74s
360:	learn: 0.1789398	total: 4.37s	remaining: 7.73s
361:	learn: 0.1788638	total: 4.38s	remaining: 7.72s
362:	learn: 0.1788332	total: 4.39s	remaining: 7.7s
363:	learn: 0.1787353	total: 4.4s	remaining: 7.69s
364:	learn: 0.1787005	total: 4.41s	remaining: 7.67s
365:	learn: 0.1786405	total: 4.42s	remaining: 7.66s
366:	learn: 0.1785846	total: 4.43s	remaining: 7.65s
367:	learn: 0.1784623	total: 4.44s	remaining: 7.63s
368:	learn: 0.1783998	total: 4.46s	remaining: 7.62s
369:	learn: 0.1783672	total: 4.47s	remaining: 7.6s
370:	learn: 0.1782860	total: 4.48s	remaining: 7.59s
371:	learn: 0.1782743	total: 4.49s	remaining: 7.58s
372:	learn: 0.1781442	total: 4.5s	remaining: 7.57s
373:	learn: 0.1780925	total: 4.52s	remaining: 7.57s
374:	learn: 0.1780269	total: 4.53s	remaining: 7.55s
375:	learn: 0.1779947	total: 4.54s	remaining: 7.54s
376:	learn: 0.1779382	total: 4.55s	remaining: 7.53s
377:	learn: 0.1778554	total: 4.57s	remaining: 7.52s
378:	learn: 0.1778226	total: 4.58s	remaining: 7.5s
379:	learn: 0.1777651	total: 4.59s	remaining: 7.49s
380:	learn: 0.1777046	total: 4.6s	remaining: 7.48s
381:	learn: 0.1775745	total: 4.62s	remaining: 7.47s
382:	learn: 0.1774960	total: 4.63s	remaining: 7.46s
383:	learn: 0.1774706	total: 4.64s	remaining: 7.45s
384:	learn: 0.1774529	total: 4.66s	remaining: 7.44s
385:	learn: 0.1774095	total: 4.67s	remaining: 7.43s
386:	learn: 0.1773535	total: 4.68s	remaining: 7.41s

In [56]:
np.mean(cv_scores)

np.float64(0.9366760773303702)

In [57]:
%%time
ctb.fit(train_df_part, y_train_part, cat_features=cat_features_idx);

Learning rate set to 0.045038
0:	learn: 0.6422781	total: 27.8ms	remaining: 27.8s
1:	learn: 0.5928701	total: 53.6ms	remaining: 26.8s
2:	learn: 0.5559396	total: 72.7ms	remaining: 24.2s
3:	learn: 0.5211198	total: 90.2ms	remaining: 22.4s
4:	learn: 0.4904617	total: 103ms	remaining: 20.5s
5:	learn: 0.4596709	total: 115ms	remaining: 19s
6:	learn: 0.4361079	total: 126ms	remaining: 17.9s
7:	learn: 0.4174589	total: 137ms	remaining: 17s
8:	learn: 0.3998322	total: 150ms	remaining: 16.5s
9:	learn: 0.3828425	total: 161ms	remaining: 16s
10:	learn: 0.3682578	total: 176ms	remaining: 15.8s
11:	learn: 0.3541550	total: 191ms	remaining: 15.7s
12:	learn: 0.3454806	total: 203ms	remaining: 15.4s
13:	learn: 0.3346755	total: 219ms	remaining: 15.4s
14:	learn: 0.3231119	total: 238ms	remaining: 15.7s
15:	learn: 0.3129339	total: 254ms	remaining: 15.6s
16:	learn: 0.3044895	total: 266ms	remaining: 15.4s
17:	learn: 0.2958288	total: 278ms	remaining: 15.2s
18:	learn: 0.2884776	total: 291ms	remaining: 15s
19:	learn: 0.2830846	total: 305ms	remaining: 14.9s
20:	learn: 0.2773779	total: 323ms	remaining: 15s
21:	learn: 0.2741335	total: 338ms	remaining: 15s
22:	learn: 0.2697147	total: 352ms	remaining: 14.9s
23:	learn: 0.2681442	total: 359ms	remaining: 14.6s
24:	learn: 0.2647501	total: 371ms	remaining: 14.5s
25:	learn: 0.2618109	total: 383ms	remaining: 14.3s
26:	learn: 0.2583815	total: 394ms	remaining: 14.2s
27:	learn: 0.2543290	total: 407ms	remaining: 14.1s
28:	learn: 0.2517494	total: 417ms	remaining: 14s
29:	learn: 0.2496522	total: 430ms	remaining: 13.9s
30:	learn: 0.2472932	total: 442ms	remaining: 13.8s
31:	learn: 0.2439129	total: 454ms	remaining: 13.7s
32:	learn: 0.2420612	total: 468ms	remaining: 13.7s
33:	learn: 0.2399561	total: 482ms	remaining: 13.7s
34:	learn: 0.2377596	total: 496ms	remaining: 13.7s
35:	learn: 0.2353873	total: 510ms	remaining: 13.6s
36:	learn: 0.2338209	total: 521ms	remaining: 13.6s
37:	learn: 0.2318078	total: 534ms	remaining: 13.5s
38:	learn: 0.2307119	total: 546ms	remaining: 13.5s
39:	learn: 0.2290046	total: 559ms	remaining: 13.4s
40:	learn: 0.2279151	total: 573ms	remaining: 13.4s
41:	learn: 0.2264856	total: 587ms	remaining: 13.4s
42:	learn: 0.2253588	total: 602ms	remaining: 13.4s
43:	learn: 0.2238330	total: 616ms	remaining: 13.4s
44:	learn: 0.2229835	total: 626ms	remaining: 13.3s
45:	learn: 0.2224131	total: 640ms	remaining: 13.3s
46:	learn: 0.2217861	total: 652ms	remaining: 13.2s
47:	learn: 0.2207970	total: 665ms	remaining: 13.2s
48:	learn: 0.2201720	total: 679ms	remaining: 13.2s
49:	learn: 0.2191134	total: 692ms	remaining: 13.1s
50:	learn: 0.2184367	total: 705ms	remaining: 13.1s
51:	learn: 0.2180736	total: 719ms	remaining: 13.1s
52:	learn: 0.2175353	total: 736ms	remaining: 13.2s
53:	learn: 0.2169755	total: 751ms	remaining: 13.2s
54:	learn: 0.2165952	total: 765ms	remaining: 13.1s
55:	learn: 0.2157623	total: 777ms	remaining: 13.1s
56:	learn: 0.2154384	total: 789ms	remaining: 13.1s
57:	learn: 0.2148838	total: 801ms	remaining: 13s
58:	learn: 0.2143285	total: 814ms	remaining: 13s
59:	learn: 0.2138604	total: 827ms	remaining: 13s
60:	learn: 0.2132050	total: 840ms	remaining: 12.9s
61:	learn: 0.2126754	total: 851ms	remaining: 12.9s
62:	learn: 0.2122703	total: 864ms	remaining: 12.8s
63:	learn: 0.2119481	total: 877ms	remaining: 12.8s
64:	learn: 0.2116514	total: 888ms	remaining: 12.8s
65:	learn: 0.2113337	total: 902ms	remaining: 12.8s
66:	learn: 0.2111048	total: 915ms	remaining: 12.7s
67:	learn: 0.2108079	total: 927ms	remaining: 12.7s
68:	learn: 0.2104996	total: 940ms	remaining: 12.7s
69:	learn: 0.2102482	total: 956ms	remaining: 12.7s
70:	learn: 0.2097188	total: 972ms	remaining: 12.7s
71:	learn: 0.2094695	total: 984ms	remaining: 12.7s
72:	learn: 0.2090214	total: 996ms	remaining: 12.6s
73:	learn: 0.2087366	total: 1.01s	remaining: 12.6s
74:	learn: 0.2085746	total: 1.02s	remaining: 12.6s
75:	learn: 0.2083277	total: 1.04s	remaining: 12.6s
76:	learn: 0.2081313	total: 1.05s	remaining: 12.6s
77:	learn: 0.2079735	total: 1.07s	remaining: 12.7s
78:	learn: 0.2077745	total: 1.08s	remaining: 12.7s
79:	learn: 0.2077197	total: 1.09s	remaining: 12.6s
80:	learn: 0.2075426	total: 1.11s	remaining: 12.6s
81:	learn: 0.2069935	total: 1.12s	remaining: 12.6s
82:	learn: 0.2067464	total: 1.13s	remaining: 12.5s
83:	learn: 0.2062967	total: 1.15s	remaining: 12.5s
84:	learn: 0.2060707	total: 1.16s	remaining: 12.5s
85:	learn: 0.2058324	total: 1.18s	remaining: 12.5s
86:	learn: 0.2056753	total: 1.19s	remaining: 12.5s
87:	learn: 0.2053902	total: 1.21s	remaining: 12.5s
88:	learn: 0.2052434	total: 1.22s	remaining: 12.5s
89:	learn: 0.2050827	total: 1.23s	remaining: 12.5s
90:	learn: 0.2049537	total: 1.25s	remaining: 12.5s
91:	learn: 0.2046306	total: 1.26s	remaining: 12.4s
92:	learn: 0.2044750	total: 1.27s	remaining: 12.4s
93:	learn: 0.2041850	total: 1.29s	remaining: 12.4s
94:	learn: 0.2040451	total: 1.3s	remaining: 12.4s
95:	learn: 0.2039007	total: 1.32s	remaining: 12.4s
96:	learn: 0.2036376	total: 1.33s	remaining: 12.4s
97:	learn: 0.2033643	total: 1.34s	remaining: 12.4s
98:	learn: 0.2032561	total: 1.35s	remaining: 12.3s
99:	learn: 0.2030913	total: 1.37s	remaining: 12.3s
100:	learn: 0.2030032	total: 1.38s	remaining: 12.3s
101:	learn: 0.2028630	total: 1.4s	remaining: 12.3s
102:	learn: 0.2027492	total: 1.41s	remaining: 12.3s
103:	learn: 0.2025770	total: 1.43s	remaining: 12.3s
104:	learn: 0.2022622	total: 1.44s	remaining: 12.3s
105:	learn: 0.2020805	total: 1.46s	remaining: 12.3s
106:	learn: 0.2018010	total: 1.48s	remaining: 12.3s
107:	learn: 0.2014215	total: 1.5s	remaining: 12.4s
108:	learn: 0.2013563	total: 1.51s	remaining: 12.4s
109:	learn: 0.2012106	total: 1.53s	remaining: 12.3s
110:	learn: 0.2011394	total: 1.54s	remaining: 12.3s
111:	learn: 0.2010728	total: 1.55s	remaining: 12.3s
112:	learn: 0.2008765	total: 1.57s	remaining: 12.3s
113:	learn: 0.2008151	total: 1.58s	remaining: 12.3s
114:	learn: 0.2006248	total: 1.6s	remaining: 12.3s
115:	learn: 0.2006190	total: 1.6s	remaining: 12.2s
116:	learn: 0.2005545	total: 1.62s	remaining: 12.2s
117:	learn: 0.2004056	total: 1.63s	remaining: 12.2s
118:	learn: 0.2003710	total: 1.64s	remaining: 12.1s
119:	learn: 0.2002662	total: 1.65s	remaining: 12.1s
120:	learn: 0.2001056	total: 1.67s	remaining: 12.1s
121:	learn: 0.1999417	total: 1.68s	remaining: 12.1s
122:	learn: 0.1997552	total: 1.7s	remaining: 12.1s
123:	learn: 0.1993766	total: 1.71s	remaining: 12.1s
124:	learn: 0.1991426	total: 1.73s	remaining: 12.1s
125:	learn: 0.1990572	total: 1.75s	remaining: 12.1s
126:	learn: 0.1989490	total: 1.76s	remaining: 12.1s
127:	learn: 0.1988097	total: 1.77s	remaining: 12.1s
128:	learn: 0.1986227	total: 1.78s	remaining: 12s
129:	learn: 0.1985679	total: 1.8s	remaining: 12s
130:	learn: 0.1984627	total: 1.81s	remaining: 12s
131:	learn: 0.1982880	total: 1.82s	remaining: 12s
132:	learn: 0.1979914	total: 1.84s	remaining: 12s
133:	learn: 0.1977539	total: 1.85s	remaining: 12s
134:	learn: 0.1976709	total: 1.86s	remaining: 11.9s
135:	learn: 0.1975855	total: 1.88s	remaining: 11.9s
136:	learn: 0.1975121	total: 1.89s	remaining: 11.9s
137:	learn: 0.1974499	total: 1.91s	remaining: 11.9s
138:	learn: 0.1973049	total: 1.93s	remaining: 11.9s
139:	learn: 0.1971353	total: 1.94s	remaining: 11.9s
140:	learn: 0.1970933	total: 1.96s	remaining: 11.9s
141:	learn: 0.1969995	total: 1.98s	remaining: 11.9s
142:	learn: 0.1969161	total: 1.99s	remaining: 12s
143:	learn: 0.1967127	total: 2.01s	remaining: 11.9s
144:	learn: 0.1966948	total: 2.02s	remaining: 11.9s
145:	learn: 0.1965814	total: 2.03s	remaining: 11.9s
146:	learn: 0.1964372	total: 2.05s	remaining: 11.9s
147:	learn: 0.1961963	total: 2.07s	remaining: 11.9s
148:	learn: 0.1960685	total: 2.08s	remaining: 11.9s
149:	learn: 0.1960209	total: 2.1s	remaining: 11.9s
150:	learn: 0.1959139	total: 2.11s	remaining: 11.9s
151:	learn: 0.1958298	total: 2.13s	remaining: 11.9s
152:	learn: 0.1957095	total: 2.14s	remaining: 11.8s
153:	learn: 0.1956019	total: 2.15s	remaining: 11.8s
154:	learn: 0.1955775	total: 2.17s	remaining: 11.8s
155:	learn: 0.1952227	total: 2.18s	remaining: 11.8s
156:	learn: 0.1949500	total: 2.19s	remaining: 11.8s
157:	learn: 0.1947702	total: 2.2s	remaining: 11.7s
158:	learn: 0.1947068	total: 2.21s	remaining: 11.7s
159:	learn: 0.1945134	total: 2.23s	remaining: 11.7s
160:	learn: 0.1944874	total: 2.24s	remaining: 11.7s
161:	learn: 0.1944315	total: 2.25s	remaining: 11.7s
162:	learn: 0.1942721	total: 2.27s	remaining: 11.7s
163:	learn: 0.1942180	total: 2.29s	remaining: 11.7s
164:	learn: 0.1941322	total: 2.3s	remaining: 11.6s
165:	learn: 0.1941095	total: 2.31s	remaining: 11.6s
166:	learn: 0.1940530	total: 2.33s	remaining: 11.6s
167:	learn: 0.1939240	total: 2.34s	remaining: 11.6s
168:	learn: 0.1937857	total: 2.35s	remaining: 11.6s
169:	learn: 0.1937328	total: 2.37s	remaining: 11.6s
170:	learn: 0.1937033	total: 2.38s	remaining: 11.5s
171:	learn: 0.1935935	total: 2.4s	remaining: 11.5s
172:	learn: 0.1935705	total: 2.41s	remaining: 11.5s
173:	learn: 0.1934929	total: 2.42s	remaining: 11.5s
174:	learn: 0.1933920	total: 2.44s	remaining: 11.5s
175:	learn: 0.1933413	total: 2.45s	remaining: 11.5s
176:	learn: 0.1932817	total: 2.46s	remaining: 11.4s
177:	learn: 0.1932130	total: 2.47s	remaining: 11.4s
178:	learn: 0.1931002	total: 2.49s	remaining: 11.4s
179:	learn: 0.1930481	total: 2.5s	remaining: 11.4s
180:	learn: 0.1929536	total: 2.52s	remaining: 11.4s
181:	learn: 0.1929043	total: 2.53s	remaining: 11.4s
182:	learn: 0.1928412	total: 2.54s	remaining: 11.4s
183:	learn: 0.1928171	total: 2.56s	remaining: 11.3s
184:	learn: 0.1927173	total: 2.57s	remaining: 11.3s
185:	learn: 0.1926749	total: 2.58s	remaining: 11.3s
186:	learn: 0.1925633	total: 2.6s	remaining: 11.3s
187:	learn: 0.1924196	total: 2.61s	remaining: 11.3s
188:	learn: 0.1923982	total: 2.62s	remaining: 11.3s
189:	learn: 0.1922558	total: 2.63s	remaining: 11.2s
190:	learn: 0.1921779	total: 2.65s	remaining: 11.2s
191:	learn: 0.1921156	total: 2.66s	remaining: 11.2s
192:	learn: 0.1919536	total: 2.67s	remaining: 11.2s
193:	learn: 0.1918247	total: 2.69s	remaining: 11.2s
194:	learn: 0.1918079	total: 2.7s	remaining: 11.1s
195:	learn: 0.1917211	total: 2.71s	remaining: 11.1s
196:	learn: 0.1916573	total: 2.73s	remaining: 11.1s
197:	learn: 0.1916303	total: 2.74s	remaining: 11.1s
198:	learn: 0.1915382	total: 2.75s	remaining: 11.1s
199:	learn: 0.1914827	total: 2.76s	remaining: 11.1s
200:	learn: 0.1912455	total: 2.78s	remaining: 11s
201:	learn: 0.1912074	total: 2.79s	remaining: 11s
202:	learn: 0.1911661	total: 2.8s	remaining: 11s
203:	learn: 0.1911157	total: 2.81s	remaining: 11s
204:	learn: 0.1910413	total: 2.83s	remaining: 11s
205:	learn: 0.1910031	total: 2.84s	remaining: 10.9s
206:	learn: 0.1908751	total: 2.85s	remaining: 10.9s
207:	learn: 0.1908589	total: 2.86s	remaining: 10.9s
208:	learn: 0.1908123	total: 2.88s	remaining: 10.9s
209:	learn: 0.1908105	total: 2.88s	remaining: 10.9s
210:	learn: 0.1908093	total: 2.89s	remaining: 10.8s
211:	learn: 0.1907533	total: 2.9s	remaining: 10.8s
212:	learn: 0.1906004	total: 2.92s	remaining: 10.8s
213:	learn: 0.1905323	total: 2.93s	remaining: 10.8s
214:	learn: 0.1904539	total: 2.94s	remaining: 10.7s
215:	learn: 0.1903509	total: 2.96s	remaining: 10.7s
216:	learn: 0.1903500	total: 2.96s	remaining: 10.7s
217:	learn: 0.1901527	total: 2.98s	remaining: 10.7s
218:	learn: 0.1901148	total: 2.99s	remaining: 10.7s
219:	learn: 0.1899259	total: 3.01s	remaining: 10.7s
220:	learn: 0.1898563	total: 3.02s	remaining: 10.7s
221:	learn: 0.1897316	total: 3.04s	remaining: 10.6s
222:	learn: 0.1897201	total: 3.05s	remaining: 10.6s
223:	learn: 0.1896369	total: 3.06s	remaining: 10.6s
224:	learn: 0.1895651	total: 3.08s	remaining: 10.6s
225:	learn: 0.1894514	total: 3.09s	remaining: 10.6s
226:	learn: 0.1894320	total: 3.1s	remaining: 10.6s
227:	learn: 0.1892093	total: 3.11s	remaining: 10.5s
228:	learn: 0.1891626	total: 3.13s	remaining: 10.5s
229:	learn: 0.1890769	total: 3.15s	remaining: 10.5s
230:	learn: 0.1889999	total: 3.16s	remaining: 10.5s
231:	learn: 0.1889110	total: 3.17s	remaining: 10.5s
232:	learn: 0.1888429	total: 3.18s	remaining: 10.5s
233:	learn: 0.1886888	total: 3.19s	remaining: 10.5s
234:	learn: 0.1886075	total: 3.21s	remaining: 10.4s
235:	learn: 0.1885419	total: 3.22s	remaining: 10.4s
236:	learn: 0.1884949	total: 3.23s	remaining: 10.4s
237:	learn: 0.1883150	total: 3.24s	remaining: 10.4s
238:	learn: 0.1882032	total: 3.26s	remaining: 10.4s
239:	learn: 0.1881752	total: 3.27s	remaining: 10.4s
240:	learn: 0.1880788	total: 3.29s	remaining: 10.4s
241:	learn: 0.1878787	total: 3.3s	remaining: 10.3s
242:	learn: 0.1878029	total: 3.31s	remaining: 10.3s
243:	learn: 0.1877171	total: 3.33s	remaining: 10.3s
244:	learn: 0.1876221	total: 3.34s	remaining: 10.3s
245:	learn: 0.1875947	total: 3.35s	remaining: 10.3s
246:	learn: 0.1875231	total: 3.37s	remaining: 10.3s
247:	learn: 0.1874214	total: 3.38s	remaining: 10.3s
248:	learn: 0.1873267	total: 3.39s	remaining: 10.2s
249:	learn: 0.1872559	total: 3.41s	remaining: 10.2s
250:	learn: 0.1872343	total: 3.42s	remaining: 10.2s
251:	learn: 0.1872098	total: 3.43s	remaining: 10.2s
252:	learn: 0.1871056	total: 3.45s	remaining: 10.2s
253:	learn: 0.1870255	total: 3.46s	remaining: 10.2s
254:	learn: 0.1869354	total: 3.47s	remaining: 10.1s
255:	learn: 0.1868466	total: 3.49s	remaining: 10.1s
256:	learn: 0.1866935	total: 3.51s	remaining: 10.1s
257:	learn: 0.1866167	total: 3.52s	remaining: 10.1s
258:	learn: 0.1865390	total: 3.54s	remaining: 10.1s
259:	learn: 0.1863470	total: 3.55s	remaining: 10.1s
260:	learn: 0.1862950	total: 3.57s	remaining: 10.1s
261:	learn: 0.1862664	total: 3.58s	remaining: 10.1s
262:	learn: 0.1862010	total: 3.59s	remaining: 10.1s
263:	learn: 0.1861573	total: 3.6s	remaining: 10s
264:	learn: 0.1859975	total: 3.61s	remaining: 10s
265:	learn: 0.1858828	total: 3.63s	remaining: 10s
266:	learn: 0.1857280	total: 3.64s	remaining: 10s
267:	learn: 0.1857174	total: 3.65s	remaining: 9.98s
268:	learn: 0.1856398	total: 3.67s	remaining: 9.96s
269:	learn: 0.1855990	total: 3.68s	remaining: 9.95s
270:	learn: 0.1854922	total: 3.69s	remaining: 9.93s
271:	learn: 0.1854449	total: 3.7s	remaining: 9.91s
272:	learn: 0.1852663	total: 3.72s	remaining: 9.9s
273:	learn: 0.1851744	total: 3.73s	remaining: 9.88s
274:	learn: 0.1850840	total: 3.74s	remaining: 9.87s
275:	learn: 0.1850124	total: 3.76s	remaining: 9.86s
276:	learn: 0.1849418	total: 3.77s	remaining: 9.84s
277:	learn: 0.1849075	total: 3.78s	remaining: 9.83s
278:	learn: 0.1848529	total: 3.79s	remaining: 9.81s
279:	learn: 0.1847843	total: 3.81s	remaining: 9.79s
280:	learn: 0.1846740	total: 3.82s	remaining: 9.78s
281:	learn: 0.1845619	total: 3.83s	remaining: 9.76s
282:	learn: 0.1845004	total: 3.84s	remaining: 9.74s
283:	learn: 0.1844517	total: 3.86s	remaining: 9.72s
284:	learn: 0.1843868	total: 3.87s	remaining: 9.71s
285:	learn: 0.1843646	total: 3.89s	remaining: 9.7s
286:	learn: 0.1843083	total: 3.9s	remaining: 9.69s
287:	learn: 0.1842872	total: 3.91s	remaining: 9.67s
288:	learn: 0.1841553	total: 3.92s	remaining: 9.65s
289:	learn: 0.1840304	total: 3.94s	remaining: 9.64s
290:	learn: 0.1839696	total: 3.95s	remaining: 9.63s
291:	learn: 0.1839039	total: 3.97s	remaining: 9.62s
292:	learn: 0.1838979	total: 3.98s	remaining: 9.6s
293:	learn: 0.1838602	total: 3.99s	remaining: 9.59s
294:	learn: 0.1838310	total: 4.01s	remaining: 9.58s
295:	learn: 0.1837894	total: 4.02s	remaining: 9.56s
296:	learn: 0.1837320	total: 4.04s	remaining: 9.55s
297:	learn: 0.1836035	total: 4.05s	remaining: 9.54s
298:	learn: 0.1835146	total: 4.06s	remaining: 9.52s
299:	learn: 0.1834730	total: 4.07s	remaining: 9.5s
300:	learn: 0.1834493	total: 4.09s	remaining: 9.49s
301:	learn: 0.1833827	total: 4.1s	remaining: 9.48s
302:	learn: 0.1833517	total: 4.11s	remaining: 9.46s
303:	learn: 0.1832845	total: 4.12s	remaining: 9.44s
304:	learn: 0.1831830	total: 4.14s	remaining: 9.43s
305:	learn: 0.1831406	total: 4.15s	remaining: 9.41s
306:	learn: 0.1830685	total: 4.16s	remaining: 9.4s
307:	learn: 0.1829707	total: 4.18s	remaining: 9.39s
308:	learn: 0.1828662	total: 4.19s	remaining: 9.37s
309:	learn: 0.1827995	total: 4.2s	remaining: 9.36s
310:	learn: 0.1826559	total: 4.22s	remaining: 9.34s
311:	learn: 0.1825480	total: 4.23s	remaining: 9.33s
312:	learn: 0.1825122	total: 4.24s	remaining: 9.31s
313:	learn: 0.1824817	total: 4.26s	remaining: 9.3s
314:	learn: 0.1823716	total: 4.27s	remaining: 9.28s
315:	learn: 0.1822817	total: 4.28s	remaining: 9.27s
316:	learn: 0.1821665	total: 4.3s	remaining: 9.26s
317:	learn: 0.1820776	total: 4.31s	remaining: 9.24s
318:	learn: 0.1819596	total: 4.32s	remaining: 9.22s
319:	learn: 0.1818477	total: 4.33s	remaining: 9.21s
320:	learn: 0.1817591	total: 4.35s	remaining: 9.2s
321:	learn: 0.1816721	total: 4.36s	remaining: 9.18s
322:	learn: 0.1816595	total: 4.38s	remaining: 9.17s
323:	learn: 0.1816522	total: 4.39s	remaining: 9.15s
324:	learn: 0.1815634	total: 4.4s	remaining: 9.14s
325:	learn: 0.1814878	total: 4.41s	remaining: 9.13s
326:	learn: 0.1813600	total: 4.43s	remaining: 9.11s
327:	learn: 0.1813155	total: 4.44s	remaining: 9.09s
328:	learn: 0.1811832	total: 4.45s	remaining: 9.08s
329:	learn: 0.1811634	total: 4.46s	remaining: 9.06s
330:	learn: 0.1811598	total: 4.48s	remaining: 9.05s
331:	learn: 0.1811533	total: 4.49s	remaining: 9.04s
332:	learn: 0.1810390	total: 4.5s	remaining: 9.02s
333:	learn: 0.1809868	total: 4.52s	remaining: 9.01s
334:	learn: 0.1808769	total: 4.53s	remaining: 9s
335:	learn: 0.1808099	total: 4.54s	remaining: 8.98s
336:	learn: 0.1807607	total: 4.56s	remaining: 8.96s
337:	learn: 0.1806469	total: 4.57s	remaining: 8.95s
338:	learn: 0.1806222	total: 4.58s	remaining: 8.94s
339:	learn: 0.1805543	total: 4.6s	remaining: 8.93s
340:	learn: 0.1804698	total: 4.61s	remaining: 8.91s
341:	learn: 0.1804337	total: 4.63s	remaining: 8.9s
342:	learn: 0.1803893	total: 4.64s	remaining: 8.88s
343:	learn: 0.1803180	total: 4.65s	remaining: 8.87s
344:	learn: 0.1802097	total: 4.66s	remaining: 8.85s
345:	learn: 0.1801728	total: 4.68s	remaining: 8.84s
346:	learn: 0.1801386	total: 4.69s	remaining: 8.83s
347:	learn: 0.1800858	total: 4.7s	remaining: 8.81s
348:	learn: 0.1800186	total: 4.71s	remaining: 8.79s
349:	learn: 0.1799567	total: 4.73s	remaining: 8.78s
350:	learn: 0.1799061	total: 4.74s	remaining: 8.77s
351:	learn: 0.1798730	total: 4.75s	remaining: 8.75s
352:	learn: 0.1797678	total: 4.77s	remaining: 8.74s
353:	learn: 0.1796663	total: 4.78s	remaining: 8.72s
354:	learn: 0.1796549	total: 4.79s	remaining: 8.71s
355:	learn: 0.1796238	total: 4.81s	remaining: 8.7s
356:	learn: 0.1795324	total: 4.82s	remaining: 8.68s
357:	learn: 0.1794312	total: 4.83s	remaining: 8.67s
358:	learn: 0.1793148	total: 4.85s	remaining: 8.65s
359:	learn: 0.1792684	total: 4.86s	remaining: 8.64s
360:	learn: 0.1792024	total: 4.87s	remaining: 8.63s
361:	learn: 0.1791267	total: 4.89s	remaining: 8.62s
362:	learn: 0.1790491	total: 4.9s	remaining: 8.6s
363:	learn: 0.1789215	total: 4.92s	remaining: 8.59s
364:	learn: 0.1789184	total: 4.93s	remaining: 8.57s
365:	learn: 0.1788401	total: 4.94s	remaining: 8.56s
366:	learn: 0.1787734	total: 4.96s	remaining: 8.55s
367:	learn: 0.1787246	total: 4.97s	remaining: 8.54s
368:	learn: 0.1786676	total: 4.99s	remaining: 8.53s
369:	learn: 0.1786101	total: 5.01s	remaining: 8.53s
370:	learn: 0.1785957	total: 5.02s	remaining: 8.51s
371:	learn: 0.1785571	total: 5.03s	remaining: 8.5s
372:	learn: 0.1785540	total: 5.04s	remaining: 8.48s
373:	learn: 0.1784936	total: 5.06s	remaining: 8.46s
374:	learn: 0.1784907	total: 5.07s	remaining: 8.45s
375:	learn: 0.1784077	total: 5.08s	remaining: 8.43s
376:	learn: 0.1783449	total: 5.09s	remaining: 8.42s
377:	learn: 0.1783426	total: 5.11s	remaining: 8.41s
378:	learn: 0.1783392	total: 5.12s	remaining: 8.39s
379:	learn: 0.1782810	total: 5.13s	remaining: 8.38s
380:	learn: 0.1782029	total: 5.15s	remaining: 8.36s
381:	learn: 0.1781846	total: 5.16s	remaining: 8.35s
382:	learn: 0.1781328	total: 5.18s	remaining: 8.34s
383:	learn: 0.1780583	total: 5.19s	remaining: 8.32s
384:	learn: 0.1780546	total: 5.2s	remaining: 8.31s
385:	learn: 0.1780493	total: 5.21s	remaining: 8.29s
386:	learn: 0.1780154	total: 5.23s	remaining: 8.28s

In [58]:
roc_auc_score(y_valid, ctb.predict_proba(valid_df)[:, 1])

0.93766370841319